fix bug on production with nil funders
54.86.91.195 - - [29/Aug/2014 07:42:29] "GET /funders_list_ids.json
HTTP/1.0" 500 30 0.0038
NoMethodError - undefined method `each' for nil:NilClass:
	/var/www/funders_ids/lib/funders.rb:83:in `to_list'
	/var/www/funders_ids/app.rb:49:in `block in <top (required)>'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in
`call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in
`block in compile!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in
`block (3 levels) in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in
`route_eval'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in
`block (2 levels) in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in
`block in process_route'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in
`catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in
`process_route'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in
`block in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in
`each'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in
`route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in
`block in dispatch!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`block in invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in
`dispatch!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in
`block in call!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`block in invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in
`invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in
`call!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in
`call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_h
eader.rb:18:in `call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_
traversal.rb:16:in `call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_
csrf.rb:18:in `call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.
rb:49:in `call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.
rb:49:in `call'

/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame
_options.rb:31:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in
`call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in
`call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in
`call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in
`call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in
`block in call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in
`synchronize'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in
`call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in
`call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in
`call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in
`call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/content_length.rb:14:in
`call'

/var/lib/gems/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in
 `process_client'

/var/lib/gems/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in
 `worker_loop'

/var/lib/gems/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in
 `spawn_missing_workers'

/var/lib/gems/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in
 `start'
	/var/lib/gems/1.9.1/gems/unicorn-4.8.3/bin/unicorn:126:in `<top
(required)>'
	/usr/local/bin/unicorn:23:in `load'
	/usr/local/bin/unicorn:23:in `<main>'